-- Generated by the database client.
CREATE TABLE nsdl.roles_master(
    role_id int IDENTITY(1,1) NOT NULL,
    role_code varchar(100) NOT NULL,
    role_name varchar(255) NOT NULL,
    visible tinyint NOT NULL DEFAULT ((1)),
    status tinyint NOT NULL DEFAULT ((1)),
    created_by int,
    created_dtm datetime NOT NULL DEFAULT (getdate()),
    modified_by int,
    modified_dtm datetime,
    PRIMARY KEY(role_id)
);
CREATE UNIQUE INDEX UQ__roles_ma__BAE63075C84BC867 ON nsdl.roles_master("role_code");