-- Generated by the database client.
CREATE TABLE nsdl.sessions(
    session_id uniqueidentifier NOT NULL DEFAULT (newid()),
    user_id int NOT NULL,
    jwt_token nvarchar(max) NOT NULL,
    is_active bit DEFAULT ((1)),
    created_at datetime DEFAULT (getdate()),
    expires_at datetime NOT NULL,
    PRIMARY KEY(session_id),
    CONSTRAINT FK__sessions__user_i__3707BEAC FOREIGN key(user_id) REFERENCES users(user_id)
);