-- Generated by the database client.
CREATE TABLE nsdl.role_permissions(
    id int IDENTITY(1,1) NOT NULL,
    role_id int NOT NULL,
    permission_id int NOT NULL,
    status tinyint NOT NULL DEFAULT ((1)),
    created_by int,
    created_at datetime NOT NULL DEFAULT (getdate()),
    updated_by int,
    updated_at datetime,
    PRIMARY KEY(id),
    CONSTRAINT FK__role_perm__role___169AEF1A FOREIGN key(role_id) REFERENCES roles_master(role_id),
    CONSTRAINT FK__role_perm__permi__178F1353 FOREIGN key(permission_id) REFERENCES permissions(id)
);