-- Generated by the database client.
CREATE TABLE nsdl.permissions(
    id int IDENTITY(1,1) NOT NULL,
    permission_code nvarchar(255) NOT NULL,
    permission nvarchar(255),
    status tinyint NOT NULL DEFAULT ((1)),
    created_by int,
    created_at datetime NOT NULL DEFAULT (getdate()),
    updated_by int,
    updated_at datetime,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX UQ__permissi__A98A808E7BFFD785 ON nsdl.permissions("permission_code");