-- Generated by the database client.
CREATE TABLE nsdl.otp_master(
    srno int IDENTITY(1,1) NOT NULL,
    user_id int,
    ur_id int,
    otp_no varchar(10) NOT NULL,
    otp_dt datetime NOT NULL DEFAULT (getdate()),
    module_nm varchar(100) NOT NULL,
    used_yn char(1) NOT NULL DEFAULT N,
    oplog_no int,
    oper1 varchar(50),
    gresponse varchar(255),
    gerrorcode varchar(50),
    gdescription varchar(255),
    PRIMARY KEY(srno),
    CONSTRAINT FK__otp_maste__user___305AC11D FOREIGN key(user_id) REFERENCES users(user_id),
    CONSTRAINT FK__otp_maste__ur_id__314EE556 FOREIGN key(ur_id) REFERENCES user_registrations(ur_id)
);